version: "3.8"

services:
  beets:
    image: lscr.io/linuxserver/beets:2.0.0
    container_name: beets
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
      - UMASK=002      
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PIP_PACKAGES=beets-audible beets-copyartifacts3 flask flask-socketio eventlet
    volumes:
      - /appdata/docker/beets/config:/config
      - /appdata/docker/beets/custom-cont-init.d:/custom-cont-init.d:ro
      - /mnt/audiobookshelf/data/audiobooks:/audiobooks
      - /mnt/audiobookshelf/data/auto-m4b/untagged:/input
    restart: unless-stopped
    ports:
      - "5000:5000"   # Webpanel-Port
      - "8337:8337"   

  auto-m4b:
    image: seanap/auto-m4b
    container_name: auto-m4b
    volumes:
      - /mnt/audiobookshelf/data/auto-m4b/recentlyadded:/temp/recentlyadded
      - /mnt/audiobookshelf/data/auto-m4b/untagged:/temp/untagged
      - /mnt/audiobookshelf/data/auto-m4b/backup:/temp/backup
      - /mnt/audiobookshelf/data/auto-m4b/delete:/temp/delete
      - /mnt/audiobookshelf/data/auto-m4b/merge:/temp/merge
      - /mnt/audiobookshelf/data/auto-m4b/fix:/temp/fix
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - CPU_CORES=4
      - SLEEPTIME=1m
      - MAKE_BACKUP=Y
      - UMASK=002
    restart: unless-stopped


