version: "3.8"

services:
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
      # Alternative: install plugins via LSIO Mods (skip step 3 if you use this)
      # - DOCKER_MODS=linuxserver/mods:universal-package-install
      # - INSTALL_PIP_PACKAGES=beets-audible beets-copyartifacts3
    volumes:
      - /appdata/docker/beets/config:/config
      - /appdata/docker/beets/scripts:/custom-cont-init.d
      - /appdata/docker/beets/services:/custom-services.d
      - /mnt/audiobookshelf/data/audiobooks:/audiobooks
      - /mnt/audiobookshelf/data/auto-m4b/untagged:/input
    restart: unless-stopped

  auto-m4b:
    image: seanap/auto-m4b
    container_name: auto-m4b
    volumes:
      - /mnt/audiobookshelf/data/downloads:/temp/recentlyadded
      - /mnt/audiobookshelf/data/auto-m4b/untagged:/temp/untagged
      - /mnt/audiobookshelf/data/auto-m4b/backup:/temp/backup
      - /mnt/audiobookshelf/data/auto-m4b/delete:/temp/delete
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - CPU_CORES=4
      - SLEEPTIME=1m
      - MAKE_BACKUP=Y
    restart: unless-stopped


