version: "3.8"

services:
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    environment:
      - PUID=1000
      - PGID=1002
      - TZ=Etc/UTC
      # Alternative: install plugins via LSIO Mods (skip step 3 if you use this)
      # - DOCKER_MODS=linuxserver/mods:universal-package-install
      # - INSTALL_PIP_PACKAGES=beets-audible beets-copyartifacts3
    volumes:
      - /appdata/docker/beets/config:/config
      - /appdata/docker/beets/scripts:/custom-cont-init.d
      - /appdata/docker/beets/services:/custom-services.d
      - /mnt/audiobookshelf/data/audiobooks:/audiobooks
      - /mnt/audiobookshelf/data/downloads:/input
    restart: unless-stopped

  m4btool:
    image: lukechidls/m4b-tool
    container_name: m4btool
    volumes:
      - /mnt/audiobookshelf/data/downloads:/downloads
      - /mnt/audiobookshelf/data/audiobooks:/audiobooks
      - /appdata/docker/beets/scripts:/scripts
    entrypoint: ["/bin/sh"]
    tty: true
    restart: unless-stopped