services:
  paperless-ai:
      image: clusterzx/paperless-ai
      container_name: paperless-ai
      network_mode: bridge
      restart: unless-stopped
      cap_drop:
        - ALL
      security_opt:
        - no-new-privileges:true
      environment:
        - PAPERLESS_AI_PORT=${PAPERLESS_AI_PORT:-3000}
        - RAG_SERVICE_URL=http://192.168.0.20:8080
        - RAG_SERVICE_ENABLED=true
        - PAPERLESS_API_URL=http://192.168.0.20/api
        - PAPERLESS_API_TOKEN=$PAPERLESS_API_TOKEN
      ports:
        - $EXTERNAL_PAPERLESS_AI_PORT:3000
      volumes:
      - $PAPERLESS_AI_DATA:/app/data
      #test
