version: "3.7"
services:
  audiobookshelf:
    container_name: audiobookshelf-server
    image: ghcr.io/advplyr/audiobookshelf:latest
    environment:
      - AUDIOBOOKSHELF_UID=${AUDIOBOOKSHELF_UID}
      - AUDIOBOOKSHELF_GID=${AUDIOBOOKSHELF_GID}
    ports:
      - "${AUDIOBOOKSHELF_HOST_PORT}:80"
    volumes:
      - ${AUDIOBOOKSHELF_AUDIOBOOKFOLDER}:/audiobooks
      - ${AUDIOBOOKSHELF_PODCASTFOLDER}:/podcasts
      - ${AUDIOBOOKSHELF_CONFIGFOLDER}:/config
      - ${AUDIOBOOKSHELF_METADATAFOLDER}:/metadata
    
    restart: unless-stopped

  apprise:
    image: lscr.io/linuxserver/apprise-api:latest
    container_name: apprise
    ports:
      - "8888:8000"
    restart: unless-stopped