FROM alpine:latest

RUN apk add --no-cache bash curl coreutils tzdata ca-certificates jq \
 && update-ca-certificates

WORKDIR /app
COPY watch_logs.sh /app/watch_logs.sh
RUN chmod +x /app/watch_logs.sh

CMD ["/app/watch_logs.sh"]
